services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  opsgate-postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opsgate
    ports:
      - "5433:5432"
    volumes:
      - ./opsgate-postgres-data:/var/lib/postgresql/data
