spring:
  liquibase:
    change-log: classpath:changelog/000-changelog.yaml
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/kviklet
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enabled: false
app:
  name: "Execution Gate"

initial:
  user:
    email: postgres
    password: postgres
