spring:
  liquibase:
    change-log: classpath:changelog/000-changelog.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/opsgate
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console.enabled: true
app:
  name: "Execution Gate"
