spring:
  liquibase:
    change-log: classpath:changelog/000-changelog.yaml
  datasource:
    url: jdbc:h2:mem:mydb;MODE=LEGACY
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        auto_quote_keyword: true
  h2:
    console.enabled: true
app:
  name: "Execution Gate"
